### ISSUE TITLE
Failure with mid360 

### ISSUE THREAD

**Issue by fratopa** [nkymzsy/LIO-SAM-MID360#6]
Hi, I am currently testing your wonderful SLAM system, however, I am having quite a few problems setting everything up.
I believe the problems stem from an improper calibration between the IMU and LiDAR frames but I can't seem to make them work
I ran some tests using[ these calibration tools](https://github.com/hku-mars/LiDAR_IMU_Init) obtaining the following results:
```
Refinement result:
Rotation LiDAR to IMU (degree)     = -4.190764 10.136540  0.457075
Translation LiDAR to IMU (meter)   =  0.019770 -0.021399  0.055599
Time Lag IMU to LiDAR (second)     = -0.080000
Bias of Gyroscope  (rad/s)         = -0.000881  0.005376 -0.002475
Bias of Accelerometer (meters/s^2) = 0.234154 0.052154 0.041102
Gravity in World Frame(meters/s^2) = -0.247655 -0.030846 -9.819398

Homogeneous Transformation Matrix from LiDAR to IMU: 
 0.984362 -0.020814  0.174923  0.019770
 0.007852  0.997192  0.074470 -0.021399
-0.175982 -0.071932  0.981762  0.055599
 0.000000  0.000000  0.000000  1.000000
```
However, since I have the sdf file of the robot I know where I placed the sensors, i.e.:
```
<link name = "lidar_link">
      <pose>0.05 0.0 0.3 0.0 0.0 0.0</pose>
```
and 
```
<link name = "imu_link">
      <pose>-0.05 0.0 0.26 0.0 0.0 0.0</pose>
```
respectively. 

If I use the geometrically accurate values for the extrinsic translation: `extrinsicTrans: [-0.1, 0, -0.04]` I obtain the following result:
![image](https://user-images.githubusercontent.com/66642543/226975456-cbd053e5-1747-4043-9430-8ad50e63040c.png)

The only way to obtain a somewhat convincing result is to set the gravity to zero:
![image](https://user-images.githubusercontent.com/66642543/226976519-d59b9c10-1a8a-4b61-bbda-cbf17c544d81.png)

I have no clue what else to try, if anyone has any idea I leave a bag here:
https://drive.google.com/drive/folders/1tDSTUFa_cjk_xvQPDTZA-OYF0lj6Kwsk?usp=sharing

**Comment by nkymzsy** [comment]
Hi, after checking the bag you provided, I think the main problem may be that Livox updated the driver file of their lidar, resulting in the code not reading the point cloud data correctly. The test code was verified based on the test prototype provided by Livox. The old driver files were used. When the product was released, livox upgraded the product driver and changed the lidar topic from livox_ros_driver::CustomMsg to livox_ros_driver2::CustomMsg.

Since we are not using this LIDAR currently, this code will no longer be updated. It is recommended that you refer to other better SLAM projects about mid360, such as [FAST_LIO](https://github.com/hku-mars/FAST_LIO).

If you want to continue using Mid360 based on the LIO-SAM framework, here are my suggestions:
1. Change the new radar message type livox_ros_driver2::CustomMsg. Debug and verify whether the data reading of each point in the point cloud is normal.
2. It is recommended to preferentially use the 9-axis imu test, which performed much better than the built-in 6-axis IMU in our experiments.

**Comment by nkymzsy** [comment]
> Hey, I solved the issue. The problem stems from the line where you convert the imu acceleration, given in g by the livox sensor. If I comment out the line `acc*=imuGravity` in the utility.h file the problem solves itself. I don't understand why setting `imuGravity: 1` doesn't achieve the same end result tho.

In the bag you provided, I found that the built-in IMU acceleration range is 9.8. However, in the version I tested earlier, the numerical value was 1, so in this version of the code, the acceleration unit was converted. Now it seems that this conversion is no longer necessary. 

setting `imuGravity: 1` doesn't achieve the same  result  is because imuGravity also  be used in the IMUPreintegration moudle.  It is a parameter  to 'gtsam::PreintegrationParams'.(  `imuPreintegration.cpp :214:     boost::shared_ptr<gtsam::PreintegrationParams> p = gtsam::PreintegrationParams::MakeSharedU(imuGravity);`). So the magnitude of this value needs to be the local actual gravitational acceleration
